"use client";
// THE VOID V2 — Lucide icon central map
// Replaces emoji UI with premium cyber-stroke icons
import {
  MessageSquare, MessageCircle, Hash, Lock,
  Send, SendHorizonal,
  Paperclip, Image as ImageIcon, FileText, Film, Music, Archive, Code2, File as FileIcon,
  Reply, Smile, SmilePlus,
  Copy, Pencil, Trash2,
  Settings, Users, UserPlus, Shield,
  Search, Plus, X, Check,
  Edit3, Palette, Info,
  LogOut, PlugZap,
  AtSign, Mail,
  ChevronLeft,
  MoreHorizontal,
  Globe, Eye,
  Zap, ShieldCheck,
  Star, Heart,
  Phone, Video,
  Bell, BellOff,
  Pin,
  Menu
} from "lucide-react";

export const Icons = {
  chat: MessageSquare,
  dm: AtSign,
  dms: MessageCircle,
  online: Users,
  settings: Settings,
  channel: Hash,
  lock: Lock,
  public: Globe,
  send: SendHorizonal,
  transmit: Send,
  attach: Paperclip,
  reply: Reply,
  react: SmilePlus,
  emoji: Smile,
  copy: Copy,
  edit: Pencil,
  delete: Trash2,
  close: X,
  add: Plus,
  check: Check,
  color: Palette,
  info: Info,
  members: Users,
  userAdd: UserPlus,
  logout: LogOut,
  disconnect: PlugZap,
  back: ChevronLeft,
  more: MoreHorizontal,
  search: Search,
  pin: Pin,
  bell: Bell,
  bellOff: BellOff,
  star: Star,
  heart: Heart,
  // file types
  file: FileIcon,
  fileText: FileText,
  image: ImageIcon,
  video: Film,
  audio: Music,
  archive: Archive,
  code: Code2,
  // brand feel
  zap: Zap,
  shield: ShieldCheck,
  menu: Menu,
};

export default Icons;
